version: "3.4"
services:
    php-fpm:
        build:
            context: docker/php-fpm
        container_name: php
        volumes:
            - .:/var/www/html

    nginx:
        image: nginx:1.13-alpine
        container_name: nginx
        volumes:
            - .:/var/www/html
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8000:8080"